# Generated by Django 5.2.7 on 2026-05-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_salaryanalytics_bonus_amount_and_more"),
        ("companies", "0003_alter_company_name_dataexchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryanalytics",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.company"
            ),
        ),
    ]
