# Generated by Django 5.2.7 on 2026-05-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompensationData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fringe_benefits_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("bonus_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("market_fairness_rating", models.IntegerField()),
                ("is_anonymous", models.BooleanField(default=True)),
                ("year", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
