# Generated by Django 5.2.7 on 2026-05-27 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_name_dataexchange"),
        ("compensation", "0002_alter_compensationdata_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compensationdata",
            name="bonus_amount",
            field=models.CharField(
                choices=[
                    ("NONE", "No bonus"),
                    ("ONE", "1 festival bonus"),
                    ("TWO", "2 festival bonuses"),
                    ("TWO_PERFORMANCE", "2 bonuses + performance"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="compensationdata",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.company"
            ),
        ),
        migrations.AlterField(
            model_name="compensationdata",
            name="fringe_benefits_value",
            field=models.CharField(
                choices=[
                    ("NONE", "No benefits"),
                    ("5K_15K", "৳5k–৳15k"),
                    ("15K_30K", "৳15k–৳30k"),
                    ("30K_PLUS", "৳30k+"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="compensationdata",
            name="market_fairness_rating",
            field=models.IntegerField(
                choices=[
                    (1, "Way below market"),
                    (2, "Slightly below market"),
                    (3, "Fair"),
                    (4, "Above market"),
                    (5, "Way above market"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="compensationdata",
            name="other_allowances",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
