# Generated by Django 5.2.7 on 2026-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0003_compensationdata_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compensationdata",
            name="fringe_benefits_value",
            field=models.CharField(
                choices=[
                    ("NONE", "No benefits"),
                    ("5K_15K", "৳5k–৳15k"),
                    ("15K_30K", "৳15k–৳30k"),
                    ("30K_PLUS", "৳30k+"),
                ],
                max_length=30,
            ),
        ),
    ]
