# Generated by Django 5.2.7 on 2026-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0004_alter_compensationdata_fringe_benefits_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compensationdata",
            name="bonus_amount",
            field=models.CharField(
                choices=[
                    ("NONE", "No bonus"),
                    ("ONE", "1 festival bonus"),
                    ("TWO", "2 festival bonuses"),
                    ("TWO_PERFORMANCE", "2 bonuses + performance"),
                ],
                max_length=30,
            ),
        ),
    ]
