# Generated by Django 5.2.7 on 2026-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0005_alter_compensationdata_bonus_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compensationdata",
            old_name="bonus_amount",
            new_name="annual_bonus_structure",
        ),
        migrations.AlterField(
            model_name="compensationdata",
            name="market_fairness_rating",
            field=models.IntegerField(
                choices=[
                    (1, "Way below market"),
                    (2, "Slightly below"),
                    (3, "Fair"),
                    (4, "Above market"),
                    (5, "Well above market"),
                ]
            ),
        ),
    ]
