# Generated by Django 5.2.7 on 2026-05-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "current_work_status",
                    models.CharField(
                        choices=[("WORKING", "Working"), ("UNEMPLOYED", "Unemployed")],
                        default="UNEMPLOYED",
                        max_length=20,
                    ),
                ),
                (
                    "current_designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "current_industry",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "current_company",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "current_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
