# Generated by Django 5.2.7 on 2026-05-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_company_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GP", "Grameenphone"),
                    ("ROBI", "Robi Axiata"),
                    ("BR", "BRAC"),
                    ("DBBL", "Dutch-bangla-bank"),
                    ("SQG", "Square Group"),
                    ("ACI", "Aci Limited"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
