# Generated by Django 5.2.7 on 2026-05-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=True)),
                ("brand_value", models.IntegerField()),
                ("work_environment", models.IntegerField()),
                ("career_growth", models.IntegerField()),
                ("salary_range_perception", models.IntegerField()),
                ("fringe_benefits", models.IntegerField()),
                ("job_security", models.IntegerField()),
                ("employee_respect", models.IntegerField()),
                ("overall_recommendation", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
