# Generated by Django 5.2.7 on 2026-05-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_name_dataexchange"),
        ("reviews", "0002_alter_companyreview_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyreview",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.company"
            ),
        ),
    ]
