# Generated by Django 5.2.7 on 2026-05-28 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_companyreview_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyreview",
            old_name="employee_respect",
            new_name="management_quality",
        ),
        migrations.RenameField(
            model_name="companyreview",
            old_name="fringe_benefits",
            new_name="overall_experience",
        ),
        migrations.RenameField(
            model_name="companyreview",
            old_name="job_security",
            new_name="salary_benefits",
        ),
        migrations.RenameField(
            model_name="companyreview",
            old_name="salary_range_perception",
            new_name="work_life_balance",
        ),
        migrations.RemoveField(
            model_name="companyreview",
            name="overall_recommendation",
        ),
        migrations.AddField(
            model_name="companyreview",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("mnc", "MNC"),
                    ("startup", "Startup"),
                    ("ngo", "NGO"),
                    ("government", "Government"),
                ],
                default='local',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyreview",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("definitely", "Definitely"),
                    ("probably", "Probably"),
                    ("neutral", "Neutral"),
                    ("probably_not", "Probably not"),
                    ("no", "No"),
                ],
                default="neutral",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
