# Generated by Django 5.2.7 on 2026-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0004_rename_employee_respect_companyreview_management_quality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyreview",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("definitely", "Definitely"),
                    ("probably", "Probably"),
                    ("neutral", "Neutral"),
                    ("probably_not", "Probably not"),
                    ("no", "No"),
                ],
                default="neutral",
                max_length=50,
            ),
        ),
    ]
