# Generated by Django 5.2.7 on 2026-05-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("MNC", "MNC"),
                            ("STARTUP", "Startup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(max_length=100)),
                (
                    "manpower_size",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10"),
                            ("11-50", "11-50"),
                            ("51-200", "51-200"),
                            ("201-500", "201-500"),
                            ("501-1000", "501-1000"),
                            ("1001-5000", "1001-5000"),
                            ("5001-10000", "5001-10000"),
                            ("10001-50000", "10001-50000"),
                            ("50001-100000", "50001-100000"),
                            ("100001+", "100001+"),
                        ],
                        max_length=20,
                    ),
                ),
                ("headquarters", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
