# Generated by Django 5.2.7 on 2026-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_name_dataexchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="manpower_size",
            field=models.CharField(max_length=20),
        ),
    ]
